name: Website

on:
  push:
    branches: [main]
    paths:
      - "packages/website/**"
      - "packages/protocol/contracts/**"
  pull_request:
    paths:
      - "packages/website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Build Website
        run: pnpm -F website build
